FROM php:8.2-apache
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN apt-get update && apt-get upgrade -y

# Increase max upload size to 20MB
RUN echo "upload_max_filesize=20M" > /usr/local/etc/php/conf.d/upload_large_dumps.ini && \
    echo "post_max_size=20M" >> /usr/local/etc/php/conf.d/upload_large_dumps.ini


#delete last docker and have it open
#terminal : 
#   docker compose down
#   docker compose up 
